### ISSUE TITLE
Add a connection diagram

### ISSUE THREAD

**Issue by srayner** [crmaykish/AT28C-EEPROM-Programmer-Arduino#1]
Can you add a connection diagram so others can see how to wire up the shield?

**Comment by nonchip** [comment]
it would also be helpful to explain how to actually erase the EEPROM without +12V being available from the arduino.

**Comment by williamhatcher** [comment]
> Can you add a connection diagram so others can see how to wire up the shield?
My pul request (#4) adds a table.

**Comment by nonchip** [comment]
a `.csv` file that doesn't follow any format or pin naming convention? and also changes a million other things? in a repo that clearly doesn't get maintained given @crmaykish already uploaded a graphical (but worse?! wow.) "diagram" without ever looking at this ticket...
wouldn't hold my breath for that to merge tbh :P
