### ISSUE TITLE
Not using -l and -o in the python tool throws TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by esalgado** [crmaykish/AT28C-EEPROM-Programmer-Arduino#3]
Hello!

Those -l and -o options, are not optional!

`  File "/home/esalgado/Downloads/AT28C-EEPROM-Programmer-Arduino/at28c_programmer.py", line 84, in main
    str(addr - args.offset[0]) + " / " + str(len(contents)))
TypeError: 'NoneType' object is not subscriptable
`

I needed to add the -l with the file size (-l 6374 ) and -o 0 for it to write data. It wrote the data perfectly.

Otherwise, excellent tool! I wanted to extend this to program AT29 chips, maybe it is as easy as adding some extra pins!! :)

**Comment by williamhatcher** [comment]
@esalgado check out my pull request for a fix!
